
namespace Snarl
{
	internal enum SNARL_COMMAND: short
	{
		SNARL_SHOW = 1,
		SNARL_HIDE,
		SNARL_UPDATE,
		SNARL_IS_VISIBLE,
		SNARL_GET_VERSION,
		SNARL_REGISTER_CONFIG_WINDOW,
		SNARL_REVOKE_CONFIG_WINDOW,
		SNARL_REGISTER_ALERT,
		SNARL_REVOKE_ALERT,
		
		SNARL_GET_REVISION = SNARL_REVOKE_ALERT, // note dual-use of command value!
		
		SNARL_REGISTER_CONFIG_WINDOW_2,
		SNARL_GET_VERSION_EX,
		SNARL_SET_TIMEOUT,
		
		/* following introduced in Snarl V39 (R2.1) */
		SNARL_SET_CLASS_DEFAULT,
		SNARL_CHANGE_ATTR,
		SNARL_REGISTER_APP,
		SNARL_UNREGISTER_APP,
		SNARL_ADD_CLASS,
		
		/* Extended commands -- all use a SNARLSTRUCTEX */
    
		SNARL_SHOW_EX = 0x20,
		SNARL_SHOW_NOTIFICATION                // V39
	}
}
